### ISSUE TITLE
Build Game

### ISSUE THREAD

**Issue by AlexProudfoot** [the-infocom-files/sherlock#2]
Build the game using the ZILF toolset. Eliminate compilation and startup errors where necessary.

**Comment by AlexProudfoot** [comment]
Ensure  the main file has a release and a version. The names of included files  should be in lower case for linux/macos compilations.

**Comment by AlexProudfoot** [comment]
The compiler reports 4 errors.
```
[error ZIL0113] parser.zil:1196: SETG: argument 1: bare atom argument must be a variable name
[error ZIL0113] parser.zil:1212: SETG: argument 1: bare atom argument must be a variable name
[error ZIL0113] parser.zil:1221: SETG: argument 1: bare atom argument must be a variable name
[error ZIL0113] parser.zil:1223: SETG: argument 1: bare atom argument must be a variable name
35 warnings (35 suppressed)
4 errors
```

**Comment by eriktorbjorn** [comment]
> The compiler reports 4 errors.
> 
> ```
> [error ZIL0113] parser.zil:1196: SETG: argument 1: bare atom argument must be a variable name
> [error ZIL0113] parser.zil:1212: SETG: argument 1: bare atom argument must be a variable name
> [error ZIL0113] parser.zil:1221: SETG: argument 1: bare atom argument must be a variable name
> [error ZIL0113] parser.zil:1223: SETG: argument 1: bare atom argument must be a variable name
> 35 warnings (35 suppressed)
> 4 errors
> ```

I don't know if it's the correct solution, but I was able to compile it by changing ```GL-P-PRSO:TABLE```, ```GL-P-PRSI:TABLE``` and ```GL-P-MERGE:TABLE``` in constants.zil from ```CONSTANT``` to ```GLOBAL```.

**Comment by AlexProudfoot** [comment]
Yes. That's the solution you would expect since we're trying to SETG those "constants". I don't remember what happened here but I successfully built this on 14/02/2020. Oh well. I'll put the fix in (again?) and close.

**Comment by eriktorbjorn** [comment]
Thanks! I guess the only games (at least of the officially released ones) that don't build out-of-the-box for me, then, are:

- Hitchhiker's Guide to the Galaxy, Solid Gold (needs lower-case filenames to ```INSERT-FILE``` in Linux)
- Planetfall, Solid Gold (needs lowe-cacse filenames to ```INSERT-FILE``` in Linux)
- Arthur (not possible to compile with ZILF 0.9?)
- Shogun (not possible to compile with ZILF 0.9?)

Of course, a few games have serious issues, but that's a different matter.
